[general]
import = [
  # "~/.config/alacritty/themes/anthropic.toml"
  # "~/.config/alacritty/themes/oneblack.toml"
  "~/.config/alacritty/themes/gruvbox-material.toml"
]


[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.8

[window.padding]
y = 18
x = 24


[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 10


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
