config_version = 14

[audio]
enable_sounds = true

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 1.0
    border = "#ffffff14"
    border_width = 1.0
    center = []
    concave_edge_corners = false
    end = [
        "tray",
        "clipboard",
        "notifications",
        "battery",
        "network",
        "bluetooth",
        "volume",
        "input_volume",
        "control-center",
        "clock"
    ]
    hover_highlight = false
    margin_edge = -1
    margin_ends = -1
    padding = 16
    radius = 0
    radius_top_left = 0
    radius_top_right = 0
    shadow = false
    start = [ "active_workspace" ]
    thickness = 38
    widget_spacing = 12

[brightness]
enable_ddcutil = true
minimum_brightness = 0.099999997764825821
sync_all_monitors = true

[control_center]
hidden_tabs = [ "weather", "screen-time" ]
sidebar = "full"
sidebar_section = "none"
width = 880

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1762.0
    cy = 1006.4000244140625
    flip_x = true
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        background_opacity = 0.0
        background_padding = 0
        background_radius = 0
        bands = 128
        color_1 = "error"
        mirrored = false
        reversed = false
        show_when_idle = false

[dock]
background_opacity = 0.99999997764825821

[hooks]
session_locked = "if [ \"$(pactl get-sink-mute alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink)\" = \"Mute: no\" ]; then pactl set-sink-mute alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink 1 && touch \"$XDG_RUNTIME_DIR/lock-muted-speaker\"; fi; for p in $(busctl --user list --no-legend | awk '$1 ~ /^org[.]mpris[.]MediaPlayer2[.]/ {print $1}'); do busctl --user call \"$p\" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player Pause; done"
session_unlocked = "if [ -e \"$XDG_RUNTIME_DIR/lock-muted-speaker\" ]; then pactl set-sink-mute alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink 0; rm -f \"$XDG_RUNTIME_DIR/lock-muted-speaker\"; fi"

[idle.behavior.lock]
enabled = true

[idle.behavior.screen-off]
enabled = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@FALLBACK",
    "lockscreen-login-box@eDP-1",
    "lockscreen-login-box@DP-1",
    "lockscreen-power@FALLBACK",
    "lockscreen-reboot@FALLBACK",
    "lockscreen-logout@FALLBACK",
    "lockscreen-power@eDP-1",
    "lockscreen-reboot@eDP-1",
    "lockscreen-logout@eDP-1",
    "lockscreen-power@DP-1",
    "lockscreen-reboot@DP-1",
    "lockscreen-logout@DP-1"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 540.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 1.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = true
        show_media = false
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 540.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
        background_color = "surface_variant"
        background_opacity = 1.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = true
        show_media = false
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 540.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 1.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = true
        show_media = false
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-logout@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1792.0
    cy = 1040.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-logout@DP-1".settings]
        background = false
        command = "noctalia msg session logout"
        glyph = "logout"
        variant = "ghost"

    [lockscreen_widgets.widget."lockscreen-logout@FALLBACK"]
    box_height = 0.0
    box_width = 0.0
    cx = 1792.0
    cy = 1040.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-logout@FALLBACK".settings]
        background = false
        command = "noctalia msg session logout"
        glyph = "logout"
        variant = "ghost"

    [lockscreen_widgets.widget."lockscreen-logout@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1792.0
    cy = 1040.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-logout@eDP-1".settings]
        background = false
        command = "noctalia msg session logout"
        glyph = "logout"
        variant = "ghost"

    [lockscreen_widgets.widget."lockscreen-power@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1880.0
    cy = 1040.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-power@DP-1".settings]
        background = false
        command = "noctalia msg session shutdown"
        glyph = "power"
        variant = "ghost"

    [lockscreen_widgets.widget."lockscreen-power@FALLBACK"]
    box_height = 0.0
    box_width = 0.0
    cx = 1880.0
    cy = 1040.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-power@FALLBACK".settings]
        background = false
        command = "noctalia msg session shutdown"
        glyph = "power"
        variant = "ghost"

    [lockscreen_widgets.widget."lockscreen-power@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1880.0
    cy = 1040.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-power@eDP-1".settings]
        background = false
        command = "noctalia msg session shutdown"
        glyph = "power"
        variant = "ghost"

    [lockscreen_widgets.widget."lockscreen-reboot@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1836.0
    cy = 1040.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-reboot@DP-1".settings]
        background = false
        command = "noctalia msg session reboot"
        glyph = "refresh"
        variant = "ghost"

    [lockscreen_widgets.widget."lockscreen-reboot@FALLBACK"]
    box_height = 0.0
    box_width = 0.0
    cx = 1836.0
    cy = 1040.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-reboot@FALLBACK".settings]
        background = false
        command = "noctalia msg session reboot"
        glyph = "refresh"
        variant = "ghost"

    [lockscreen_widgets.widget."lockscreen-reboot@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1836.0
    cy = 1040.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget."lockscreen-reboot@eDP-1".settings]
        background = false
        command = "noctalia msg session reboot"
        glyph = "refresh"
        variant = "ghost"

[nightlight]
enabled = true

[notification]
background_opacity = 0.99999997764825821

[osd]
background_opacity = 1.0
offset_y = 20
position = "bottom_center"
position_vertical = "bottom_right"

    [osd.kinds]
    media = false

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"

[plugin_settings."tadomika_ari/w-engine"]
w-engine-panel_position = "center"

[plugins]
enabled = [ "raphael/hypr-displays", "raphael/hypr-active-workspace", "raphael/hypr-shots" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "/home/raphael/.config/noctalia-plugins"
    name = "dev"

[shell]
button_borders = false
input_borders = false
polkit_agent = true
settings_window_translucent = false

    [shell.animation]
    speed = 2.0000000298023224

    [shell.greeter_sync]
    auto_sync = true

    [shell.keyboard_layout.custom_labels]
    "English (US)" = "EN"
    "Portuguese (Brazil)" = "BR"

    [shell.launcher]
    categories = false
    fetch_exchange_rates = false
    show_app_origin_indicator = false

        [shell.launcher.providers.calculator]
        global = false

    [shell.mpris]
    blacklist = [ "firefox" ]

    [shell.panel]
    clipboard_placement = "floating"
    clipboard_position = "top_center"
    control_center_placement = "floating"
    open_near_click_launcher = true
    session_placement = "floating"
    session_position = "top_center"
    wallpaper_placement = "floating"
    wallpaper_position = "top_center"

    [shell.screenshot]
    confirm_region = true
    directory = "/home/raphael/Pictures/Screenshots"

    [shell.shadow]
    alpha = 0.34999999999999998

[theme]
builtin = "Kanagawa"
community_palette = "ADW"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4" ]
    community_ids = [ "spicetify", "zen-browser", "discord", "libreoffice", "obs", "zathura", "hyprtoolkit" ]

[wallpaper]
directory = "/home/raphael/Pictures/Wallpaper"

    [wallpaper.default]
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"

    [wallpaper.last]
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"

    [[wallpaper.favorite]]
    community_palette = "Gruvbox Material Hard"
    palette_source = "community"
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"
    theme_mode = "auto"

[widget.active_window]
display = "text_only"
font_weight = 700
max_length = 380

[widget.active_workspace]
font_weight = 600
format = "Desktop {name}"
type = "raphael/hypr-active-workspace:active-workspace"

[widget.audio_visualizer]
bands = 40
color_1 = "error"
color_2 = "tertiary"
mirrored = false
width = 40

[widget.battery]
display_mode = "graphic"
hide_when_full = true
hide_when_plugged = true
scale = 0.80000000000000004
show_label = false

[widget.bluetooth]
hide_when_adapter_off = true
hide_when_no_connected_device = true

[widget.brightness]
show_label = false

[widget.clock]
format = "{:%a. %-d de %b. %H:%M}"

[widget.control-center]
glyph = "adjustments-horizontal"

[widget.input_volume]
hide_when_inactive = true
show_label = false

[widget.network]
show_label = false
show_vpn_label = true

[widget.notifications]
hide_when_no_unread = true

[widget.tray]
color = "on_surface"
detached_panel = true
drawer = true

[widget.volume]
hide_when_inactive = true
show_label = false