config_version = 14

[audio]
enable_sounds = true

[bar.default]
center = [ "clock", "wallhaven" ]
concave_edge_corners = false
contact_shadow = true
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "session", "battery" ]
font_weight = 600
hover_highlight = false
margin_ends = 0
padding = 12
radius = 0
start = [ "active_workspace" ]
widget_spacing = 8

[brightness]
enable_ddcutil = true
minimum_brightness = 0.099999997764825821
sync_all_monitors = true

[control_center]
hidden_tabs = [ "weather", "screen-time" ]
show_session_button = false
show_shortcut_labels = false
width = 720

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "notification"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1762.0
    cy = 1006.4000244140625
    flip_x = true
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        background_opacity = 0.0
        background_padding = 0
        background_radius = 0
        bands = 128
        color_1 = "error"
        mirrored = false
        reversed = false
        show_when_idle = false

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 807.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"

[plugin_settings."tadomika_ari/w-engine"]
w-engine-panel_position = "center"

[plugins]
enabled = [ "raphael/hypr-shots", "raphael/hypr-displays", "raphael/hypr-active-workspace" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "/home/raphael/.config/noctalia-plugins"
    name = "dev"

[shell]
button_borders = false
corner_radius_scale = 0.0
font_family = "JetBrainsMono Nerd Font"
input_borders = false
polkit_agent = true
settings_show_advanced = false
settings_window_translucent = true

    [shell.animation]
    speed = 2.0000000298023224

    [shell.greeter_sync]
    auto_sync = true

    [shell.keyboard_layout.custom_labels]
    "English (US)" = "EN"
    "Portuguese (Brazil)" = "BR"

    [shell.launcher]
    compact = true

    [shell.panel]
    transparency_mode = "glass"

    [shell.screenshot]
    confirm_region = true
    directory = "/home/raphael/Pictures/Screenshots"

[theme]
builtin = "Gruvbox"
community_palette = "Gruvbox Material Hard"
pure_black_dark = true
source = "community"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "qt" ]
    community_ids = [ "spicetify", "zen-browser", "discord", "libreoffice", "obs", "zathura", "hyprtoolkit" ]

[wallpaper]
directory = "/home/raphael/Pictures/Wallpaper"

    [wallpaper.default]
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"

    [wallpaper.last]
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"

    [[wallpaper.favorite]]
    community_palette = "Gruvbox Material Hard"
    palette_source = "community"
    path = "/home/raphael/Pictures/Wallpaper/forest-4.jpg"
    theme_mode = "auto"

[weather]
enabled = false

[widget.active_workspace]
type = "raphael/hypr-active-workspace:active-workspace"

[widget.audio_visualizer]
bands = 40
color_1 = "error"
color_2 = "tertiary"
mirrored = false
width = 40

[widget.battery]
display_mode = "graphic"
scale = 0.75
show_label = false

[widget.brightness]
show_label = false

[widget.clock]
format = "{:%D %H:%M}"

[widget.network]
show_label = false

[widget.notifications]
hide_when_no_unread = true

[widget.tray]
color = "on_surface"

[widget.volume]
show_label = false

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"